language: node_js
sudo: false
node_js: 6.7.0
edge: true
script:
- ". ./scripts/run_test.sh"
deploy:
  provider: cloudfoundry
  api: https://api.ng.bluemix.net
  username: valerio.riva@it.ibm.com
  password:
    secure: nCleww+yR15viZrfmRqKG5UiMLYgQA4E3K6fnxMXIRlfTLcvjYkaxRRKK1LjuSYHCkGSe8dJKWyzKPJEcj5BybCa3spwTHsGF4vbR1bl0Ijs7jJ64tnBYoLuf49ChADaVElkv9W3+n0zSq60A7rSjbQdM8ycnJWtgofpi5c+7BCDTQIVxCzT3qFi4eZHs7kiQTrve0EOcobGzwou9hrKtTnurXBXsEKb/WQZQeHZxrVwSk/D/J2u6n1HfmIlti8EQhzSjW6X56Q/0bfV28Y0ZxIuRNFNYo31WPEFnmmmvAGrzJybVDg2tC6o/KlmUaK86PiAhouPMDbCWhemU5ilMdruVSzNh9s/HQOtZcg9ZjA3x7XyCHBTyqW+kjwNhkaIpPszP00pXJybQMdn8CjYoAg1UltMV3giXr1sKA6/K/nD1wGITneRLkpBd0GNzSSaY6suTfi/emIZ8WUr6V+LrpOlItHHI3IO8t1E7r9cuyw1ncyjHFmsOSK2Ui1m0oTdhZCwvCai1JstC60btWoNSE+siCWREHFZM/4ykLucGfsbGZ+DZArsM5p0xReYTqyoiXM9Ve6Zei0VYIBNucJ4VJCn0CpRJggOBqsqnlRdrrGoUTNVx7LNnj47UMunBudtBZoYY9//L0WiYOG0fW2dLo+hemOgZNGKqdyqPH/KgGI=
  organization: valerio.riva@it.ibm.com
  space: devUSSouth
  on:
    repo: Lotti/to-do-list
