language: node_js
sudo: false
node_js: 6.7.0
edge: true
script:
- . ./scripts/run_test.sh
- . ./scripts/run_coverage.sh
deploy:
  provider: cloudfoundry
  api: https://api.ng.bluemix.net
  username: valerio.riva@it.ibm.com
  password:
    secure: q7G1J4iSqMnqxbvd7ox0NAxYhs9tyDBipqJeEJQYa/VkhHziv64DZ/lR7MODRjZu8LktxEDaWdeiWpISR30G91Sko0L6yU7hXSL2HKfoAZq0VaN4/kHGlgW5y2oBMByRPZ/Dg2wDLkIDn7+/OMmv54RhX7lbfrgkOI/JhW+XV/jtA5pQokYbaLiMje6gg/Xe25Z79ONb0W9DfSb0O71MMtvTQZMkJknSrs9SHRaDLN6S6SQcNJP0OqLn1YXgp+DrFtxrdTiXzAJ8GkIaG7r7R9SZsPIXY5tzZQjTbp63DBsDBrybKIrUvHTcN5XwzBnMOt0QKGjaBU0f7VWSTuG+HJ6ZDL1cvVeoljOnjm2+RCMg6L3IllUfgN41YCL3PtiBpN3QQRw+RSU5WpjO07/9DmVb7LyBHWAJO2wqEMl/FxJZRa0LnlzRHcNSWJGJkkcyz6UJCCfZe7uPqYJBPuPtdbjbTBHkNjJzRpW8gB8YOnxLCv6FSO77UC8tTtEWQyU4rzg1WBoxnTDez/BV84Av3a1++1XwWMC2eZL4DkscPQLhZLrRZAgTh/eSmSW2cF/qxiiptddwtPwXE02Xj/J17vXQJUqW5lNlkEQJBdqUuzmSP5g4e7HFM6iFx0x7mtv8HT3MOdb209UkBNNjR6k3G6oLFCCW9SU8xr/n/DZwRu8=
  organization: valerio.riva@it.ibm.com
  space: devUSSouth
  on:
    repo: valerio-riva/to-do-list
